# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- build
- test
- lint

build:
  stage: build
  image: electronuserland/builder:wine
  before_script:
    - npm install
  script:
    - npm run build:win

unit-test:
  stage: test
  image: norf/node-electron-test:20.1.0
  before_script:
    - npm install
  script:
    - npm run build:linux
    - export DISPLAY=:99.0
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - npm run wdio


linting:
  image: node:latest
  stage: lint

  script:
    - npm i eslint eslint-plugin-react eslint-plugin-jsdoc eslint-plugin-prettier eslint-config-prettier
  # run eslint
    - npm run lint
    - node_modules/eslint/bin/eslint.js .